import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/providers";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="bg-[#c1deff]">
            <header className="max-w-7xl mx-auto px-2 sm:px-0">
              <Header />
            </header>
            <main className="min-h-screen mx-auto max-w-7xl mt-4 px-5 py-6">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
